### ISSUE TITLE
generate_meter_data.py format

### ISSUE THREAD

**Issue by voycey** [aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform#31]
Hi,

Is there any reason why the meter data is output in the format that it is? It doesn't seem to match up with any of the formats in the ETL pipeline?

The dataset for the London data has been removed but taking the one from Kaggle you can see that the London data for example has a structure of:

```
LCLid,stdorToU,DateTime,KWH/hh (per half hour) ,Acorn,Acorn_grouped
MAC000036,Std,2012-11-08 10:30:00.0000000, 0.003 ,ACORN-E,Affluent
```

Whereas the generated data has something more like:

```
46001|2.8.3|2019010100240000|45.218|AGG|spid|rq|ansi|smult|DST|AccNum|sqcode
46001|1.8.1|2019010100240000|26.492|INT|spid|rq|ansi|smult|DST|AccNum|sqcode
46001|1.8.0|2019010100240000|31.191|INT|spid|rq|ansi|smult|DST|AccNum|sqcode
```

Is there a reason the fields are added to the end? Is this some other meter data format?
Just curious as the ability to generate meter data like this would be invaluable for our testing

**Comment by sj5n** [comment]
Hi @voycey, 
the ETL pipeline is able to handle different meter formats, because around the world different MDM Systems produce different data files. The MDA Quick Starts comes with two different input adapter which can be selected during deployment. The default one parses the London demo data, the second one parses the data which get generated by the generator. This is described in the documentation ([here](https://aws-quickstart.github.io/quickstart-aws-utility-meter-data-analytics-platform/#_download_sample_demo_dataset)). 

The generator produces just another meter reading format, this format is based on MDMS exports we have seen in different projects. Currently the MDA just uses the first five fields, the trailing fields are reserved for future use.

**Comment by voycey** [comment]
Hi Sascha - thanks for this, didn't realise there was a different input adapter - ill check out the different formats - thanks!
